# Generated by Django 5.1.2 on 2025-03-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='announcement_content')),
                ('related_to', models.CharField(choices=[('D', 'Domain Based'), ('T', 'Task'), ('M', 'Manual Selection')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivers', models.ManyToManyField(related_name='announcement_receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annoucement_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
