# Generated by Django 5.1.5 on 2025-02-12 18:46

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('domain_based', [('backend_2_3', 'Backend (2+3)'), ('frontend_2_3', 'Frontend (2+3)'), ('ml_2_3', 'Machine Learning (2+3)'), ('designers_2_3', 'Designers (2+3)'), ('app_dev_2_3', 'App Development (2+3)')]), ('year_based', [('2nd_year', '2nd Year'), ('3rd_year', '3rd Year'), ('4th_year', '4th Year')]), ('general_chat', [('CSI_2_3', 'CSI (2+3)'), ('CSI_2_3_4', 'CSI (2+3+4)')])], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='room_avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('reaction', 'Reaction')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment')),
                ('reactions', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in', to=settings.AUTH_USER_MODEL)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Chat.room')),
            ],
        ),
    ]
