# Generated by Django 5.1.2 on 2025-03-06 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_userroomstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroomstatus',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='Chat.room'),
        ),
        migrations.AlterField(
            model_name='userroomstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
