# Generated by Django 5.1.5 on 2025-02-10 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('previous', 'previous')], default='upcoming', max_length=20)),
                ('registration_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_registrations_open', models.BooleanField(default=False)),
                ('media_files', models.ManyToManyField(blank=True, to='Media.mediafile')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
