# Generated by Django 5.1.5 on 2025-02-09 10:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('APP_DEV', 'App Development'), ('ML', 'Machine Learning'), ('DESIGNER', 'Designer')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image representing this domain.', max_length=255, null=True, verbose_name='image')),
                ('goals', models.TextField(blank=True, help_text='Goals of the domain.', null=True)),
            ],
        ),
    ]
