# Generated by Django 5.1.5 on 2025-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('APP_DEV', 'App Development'), ('ML', 'Machine Learning'), ('UI/UX_DEV', 'UI/UX Development'), ('FULL_STACK', 'Full Stack Development')], max_length=20, unique=True),
        ),
    ]
