# Generated by Django 5.1.2 on 2025-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_task_assigned_to_alter_task_assigned_by_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Task'), ('current', 'Current Task'), ('completed', 'Completed Task')], default='current', max_length=50),
        ),
    ]
