# Generated by Django 5.1.2 on 2025-02-26 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CS-IT', 'CS-IT'), ('CSE-DS', 'CSE-DS'), ('CS-HINDI', 'CS-HINDI'), ('CSE-AIML', 'CSE-AIML'), ('IT', 'IT'), ('AIML', 'AIML'), ('ECE', 'ECE'), ('ME', 'ME'), ('EN', 'EN'), ('CIVIL', 'CIVIL')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('hosteller', models.BooleanField()),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
