# Generated by Django 5.1.2 on 2025-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CS-IT', 'CS-IT'), ('CSE-DS', 'CSE-DS'), ('CS-HINDI', 'CS-HINDI'), ('CSE-AIML', 'CSE-AIML'), ('IT', 'IT'), ('AIML', 'AIML'), ('ECE', 'ECE'), ('ME', 'ME'), ('EN', 'EN'), ('CIVIL', 'CIVIL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
