# Generated by Django 5.1.2 on 2025-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_user_achievements_user_branch_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hosteller',
            field=models.BooleanField(default=False),
        ),
    ]
